version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: metro-react-native-babel-preset
    versions:
    - 0.65.0
    - 0.65.1
    - 0.65.2
  - dependency-name: react-native-gesture-handler
    versions:
    - 1.10.0
    - 1.10.1
    - 1.10.2
    - 1.9.0
  - dependency-name: "@react-navigation/native"
    versions:
    - 5.9.2
    - 5.9.3
  - dependency-name: react-native-safe-area-context
    versions:
    - 3.1.9
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: "@eva-design/eva"
    versions:
    - 2.0.0
